plugins {
    id 'com.android.application'
}

android {
    namespace 'kr.modelbeauty'
    compileSdk 36

    defaultConfig {
        applicationId "kr.modelbeauty"
        minSdk 24
        targetSdk 36
        versionCode 15
        versionName "1.0.15"

        testInstrumentationRunner "androidx.test.runner.AndroidJUnitRunner"
    }

    signingConfigs {
        release {
            storeFile file("C:/Users/myday/modelbeauty_key.jks")
            storePassword "modelbeauty123!"
            keyAlias "key0"
            keyPassword "modelbeauty123!"
        }
    }

    buildTypes {
        release {
            signingConfig signingConfigs.release
            minifyEnabled true
            proguardFiles getDefaultProguardFile('proguard-android-optimize.txt'), 'proguard-rules.pro'
        }
    }
    compileOptions {
        sourceCompatibility JavaVersion.VERSION_17
        targetCompatibility JavaVersion.VERSION_17
    }
}

dependencies {
    implementation 'androidx.appcompat:appcompat:1.6.1'
    implementation 'com.google.android.material:material:1.11.0'
    implementation 'androidx.constraintlayout:constraintlayout:2.1.4'
    implementation 'androidx.activity:activity:1.8.2'
}
